CREATE TABLE IF NOT EXISTS pinprof_machine_overrides (
  practice_identity VARCHAR(64) NOT NULL PRIMARY KEY,
  opdb_machine_id VARCHAR(128) NULL,
  slug VARCHAR(255) NULL,
  name_override VARCHAR(255) NULL,
  variant_override VARCHAR(255) NULL,
  manufacturer_override VARCHAR(255) NULL,
  year_override INT NULL,
  backglass_local_path VARCHAR(255) NULL,
  backglass_source_url TEXT NULL,
  backglass_source_note TEXT NULL,
  playfield_local_path VARCHAR(255) NULL,
  playfield_source_url TEXT NULL,
  playfield_source_note TEXT NULL,
  rulesheet_local_path VARCHAR(255) NULL,
  rulesheet_source_url TEXT NULL,
  rulesheet_source_note TEXT NULL,
  gameinfo_local_path VARCHAR(255) NULL,
  notes MEDIUMTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_pinprof_machine_overrides_slug (slug),
  KEY idx_pinprof_machine_overrides_opdb_machine_id (opdb_machine_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
